"""empty message

Revision ID: 142ee4a5d31c
Revises: eb140ff4ace5
Create Date: 2019-06-29 19:42:57.781382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142ee4a5d31c'
down_revision = 'eb140ff4ace5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('black', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest', 'black')
    # ### end Alembic commands ###
