"""empty message

Revision ID: 4c2ff31abec3
Revises: cc95968d53c3
Create Date: 2019-06-29 17:48:04.894407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c2ff31abec3'
down_revision = 'cc95968d53c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'statu')
    op.drop_column('comment', 'guest_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('guest_name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('comment', sa.Column('statu', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
