"""empty message

Revision ID: 99a67c333a6c
Revises: 0c4da0674c02
Create Date: 2019-06-29 18:03:20.233763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a67c333a6c'
down_revision = '0c4da0674c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist')
    op.add_column('guest', sa.Column('state', sa.Boolean(), nullable=True))
    op.drop_column('guest', 'statu')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('statu', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('guest', 'state')
    op.create_table('blacklist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
