"""empty message

Revision ID: cc95968d53c3
Revises: 
Create Date: 2019-06-29 17:46:19.359542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc95968d53c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('guest_name', sa.String(length=32), nullable=True))
    op.add_column('comment', sa.Column('statu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'statu')
    op.drop_column('comment', 'guest_name')
    # ### end Alembic commands ###
