"""empty message

Revision ID: e99c8719098e
Revises: b2e94361a1f0
Create Date: 2019-06-29 20:04:34.537582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99c8719098e'
down_revision = 'b2e94361a1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('guest_name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'guest_name')
    # ### end Alembic commands ###
