"""empty message

Revision ID: eb140ff4ace5
Revises: 99a67c333a6c
Create Date: 2019-06-29 18:56:34.788887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb140ff4ace5'
down_revision = '99a67c333a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'state')
    # ### end Alembic commands ###
